# Generated by Django 4.0.3 on 2022-03-17 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnitures_api', '0002_furniture_color_furniture_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furniture',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
