# Generated by Django 4.0.3 on 2022-03-20 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furnitures_api', '0002_remove_furniture_comment_remove_furniture_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
    ]
