# Generated by Django 4.0.3 on 2022-03-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnitures_api', '0006_remove_cart_category_remove_cart_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='category',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='availability',
            field=models.BooleanField(default=True),
        ),
    ]
