# Generated by Django 4.0.3 on 2022-03-18 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnitures_api', '0008_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='product',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
